image:
  repository: <your-username>/kong-gateway
  tag: "1.0"

# Admin API, To interract with the kong configuration
admin:
  enabled: true
  type: LoadBalancer
  http:
    enabled: true
  tls:
    enabled: false

# Important
plugins:
  configMaps:
  - pluginName: kong-auth-integration
    name: kong-plugin-kong-auth-integration

# You need enabled this env
env:
  database: "postgres"

# Use this if we used internal database
postgresql:
  enabled: true
  auth:
    postgresPassword: kong
    password: kong

# you can enable if you want
ingressController:
  enabled: false

# We disable the manager since we will use Admin PI
manager:
  enabled: false
